// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zajhytlmhtrgikcvluqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inphamh5dGxtaHRyZ2lrY3ZsdXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTIzMzgsImV4cCI6MjA2MTg2ODMzOH0.wADkF4MHd3_B3rOYQImvJoz9-onw1BlaxLxdkdq88qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);